name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
      - master
      - feature/cicd

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirementsDocs.txt

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
