name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
      - master
      - feature/cicd

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
          architecture: "x64"

      - name: Deploy docs
        uses: afritzler/mkdocs-gh-pages-action@v8.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: ./requirementsDocs.txt
