name: molecule e2e

on:
  push:
    paths-ignore:
    - 'docs/**'
    - 'requirementsDocs.txt'
    - '.devcontainer'


jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2.3.4
     - uses: actions/setup-python@v2
       with:
         python-version: 3.9
         architecture: 'x64'
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         ls -all
         pip install -r ./requirementsDev.txt
     - name: Test with molecule
       run: molecule test
#/go/src/github.com/nolte/ansible_playbook-baseline-online-server/molecule/default
